# # -*- coding: utf-8 -*-
# """OCR

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1Ir_Y1vLDoVV8x88Svb8RxKiFXgwNmaN7
# """

# !pip install easyocr

# !pip install opencv-python

# import easyocr
# import cv2
# from matplotlib import pyplot as plt
# import numpy as np

# import easyocr
# import cv2
# from matplotlib import pyplot as plt
# import numpy as np

# # Load EasyOCR reader
# reader = easyocr.Reader(['en'])  # 'en' = English

# # Load image
# image_path = "C:/Users/Pray/OneDrive/Desktop/Surfing.jpg"
# results = reader.readtext(image_path)

# # Print text only
# for (bbox, text, prob) in results:
#     print(f"Text: {text}   |   Confidence: {prob}")

# import easyocr
# import cv2
# from matplotlib import pyplot as plt
# import numpy as np

# # Load EasyOCR reader
# reader = easyocr.Reader(['en'])  # English OCR model

# # Load image (USE RAW STRING FOR WINDOWS PATH)
# image_path = "Surfing.jpg"

# # Run OCR
# results = reader.readtext(image_path)

# # Print text only
# for (bbox, text, prob) in results:
#     print(f"Text: {text}   |   Confidence: {prob}")

# import easyocr
# import cv2

# reader = easyocr.Reader(['en'])
# image_path = "Surfing.jpg"

# results = reader.readtext(image_path)
# img = cv2.imread(image_path)

# for (bbox, text, prob) in results:
#     pt1 = tuple([int(bbox[0][0]), int(bbox[0][1])])
#     pt2 = tuple([int(bbox[2][0]), int(bbox[2][1])])
#     cv2.rectangle(img, pt1, pt2, (0,255,0), 2)
#     cv2.putText(img, text, pt1, cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)

# cv2.imwrite("Surfing_annotated.jpg", img)
# print("Annotated image saved as Surfing_annotated.jpg")

# !pip install --upgrade
# !pip install easyocr opencv-python pandas openpyxl
# # EasyOCR needs PyTorch; install CPU wheel if you don't have G
# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# """
# easyocr_to_excel.py
# - Usage examples:
#     python easyocr_to_excel.py --input "C:/Users/Pray/OneDrive/Desktop/Surfing.jpg"
#     python easyocr_to_excel.py --input "C:/Users/Pray/OneDrive/Desktop/images_folder" --out "C:/Users/Pray/OneDrive/Desktop/ocr_out" --annotate

# - Output:
#     ocr_results.xlsx  (columns: filename, filepath, text, confidence, xmin, ymin, xmax, ymax)
#     annotated images (if --annotate)
# """
# import os
# import argparse
# from pathlib import Path
# import easyocr
# import cv2
# import pandas as pd

# VALID_EXT = {'.jpg', '.jpeg', '.png', '.bmp', '.tif', '.tiff'}

# def get_image_paths(p):
#     p = Path(p)
#     if p.is_file():
#         return [p]
#     elif p.is_dir():
#         return sorted([x for x in p.rglob('*') if x.suffix.lower() in VALID_EXT])
#     else:
#         raise FileNotFoundError(f"Path not found: {p}")

# def bbox_to_xy(bbox):
#     xs = [pt[0] for pt in bbox]
#     ys = [pt[1] for pt in bbox]
#     xmin, xmax = min(xs), max(xs)
#     ymin, ymax = min(ys), max(ys)
#     return int(round(xmin)), int(round(ymin)), int(round(xmax)), int(round(ymax))

# def annotate_and_save(img_bgr, detections, out_path):
#     img = img_bgr.copy()
#     for bbox, text, conf in detections:
#         xmin, ymin, xmax, ymax = bbox_to_xy(bbox)
#         cv2.rectangle(img, (xmin, ymin), (xmax, ymax), (0,255,0), 2)
#         label = f"{text} ({conf:.2f})"
#         (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
#         y0 = max(ymin - th - 6, 0)
#         cv2.rectangle(img, (xmin, y0), (xmin + tw + 6, y0 + th + 6), (0,255,0), -1)
#         cv2.putText(img, label, (xmin+3, y0+th+1), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
#     cv2.imwrite(str(out_path), img)

# def run(input_path, out_dir, langs=['en'], gpu=False, min_conf=0.2, annotate=False):
#     reader = easyocr.Reader(langs, gpu=gpu)
#     image_paths = get_image_paths(input_path)
#     out_dir = Path(out_dir)
#     out_dir.mkdir(parents=True, exist_ok=True)
#     annotated_dir = out_dir / 'annotated'
#     if annotate:
#         annotated_dir.mkdir(exist_ok=True)

#     rows = []
#     for img_path in image_paths:
#         img_bgr = cv2.imread(str(img_path))
#         if img_bgr is None:
#             print(f"Warning: could not read image {img_path}, skipping.")
#             continue
#         img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
#         try:
#             results = reader.readtext(img_rgb)
#         except Exception as e:
#             print(f"EasyOCR failed on {img_path}: {e}")
#             results = []

#         for bbox, text, conf in results:
#             if conf < min_conf:
#                 continue
#             xmin, ymin, xmax, ymax = bbox_to_xy(bbox)
#             rows.append({
#                 'filename': img_path.name,
#                 'filepath': str(img_path),
#                 'text': text,
#                 'confidence': float(conf),
#                 'xmin': xmin,
#                 'ymin': ymin,
#                 'xmax': xmax,
#                 'ymax': ymax
#             })

#         if annotate:
#             out_ann = annotated_dir / f"{img_path.stem}_annotated{img_path.suffix}"
#             annotate_and_save(img_bgr, results, out_ann)

#     # Save to Excel
#     df = pd.DataFrame(rows, columns=['filename','filepath','text','confidence','xmin','ymin','xmax','ymax'])
#     excel_path = out_dir / 'ocr_results.xlsx'
#     df.to_excel(str(excel_path), index=False, engine='openpyxl')
#     print(f"Saved {len(df)} detections to {excel_path}")

# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--input','-i', required=True, help='image path or folder')
#     parser.add_argument('--out','-o', default='easyocr_output', help='output directory')
#     parser.add_argument('--lang','-l', nargs='+', default=['en'], help='languages e.g. en hi')
#     parser.add_argument('--gpu', action='store_true', help='use GPU (requires CUDA torch)')
#     parser.add_argument('--min_conf', type=float, default=0.2, help='minimum confidence to keep detection')
#     parser.add_argument('--annotate', action='store_true', help='save annotated images')
#     args = parser.parse_args()
#     run(args.input, args.out, langs=args.lang, gpu=args.gpu, min_conf=args.min_conf, annotate=args.annotate)

# import pytesseract
# import pandas as pd
# from PIL import Image
# import os
# # We no longer need 'requests' or 'io' since the file is local

# # --- 2. Define File Paths ---
# # Use the filename of your uploaded image directly
# image_filename = "Surfing.jpg"  # <<< REVISED TO USE YOUR UPLOADED FILE NAME

# output_excel_filename = "ocr_surfing_data.xlsx"

# # --- 3. Image Loading ---
# try:
#     # Check if the file exists in the current Colab working directory
#     if not os.path.exists(image_filename):
#         print(f"Error: The file '{image_filename}' was not found.")
#         print("Please ensure you have uploaded 'Surfing.jpg' to the Colab session files.")
#     else:
#         # Open the local image file using PIL (Pillow)
#         img = Image.open(image_filename)

#         print(f"--- Successfully loaded image: {image_filename} ---")
#         display(img) # Display the image for verification

#         # --- 4. Extract Detailed OCR Data (Bounding Boxes) ---
#         # The output_type=pytesseract.Output.DATAFRAME returns data with coordinates.
#         ocr_data_df = pytesseract.image_to_data(img, output_type=pytesseract.Output.DATAFRAME)

#         # --- 5. Clean and Filter the Data ---
#         # Filter out rows where the 'text' is null/empty (these are usually borders or noise)
#         cleaned_df = ocr_data_df.dropna(subset=['text'])
#         cleaned_df = cleaned_df[cleaned_df['text'].str.strip() != '']

#         # --- 6. Save to Excel ---
#         # Save the Pandas DataFrame to an Excel file.
#         cleaned_df.to_excel(output_excel_filename, index=False)

#         print(f"\n✅ Success! OCR data with bounding boxes saved to: {output_excel_filename}")

#         # Display the extracted text and coordinates for verification
#         print("\n--- Extracted Data (Columns: left, top, width, height, text) ---")
#         print(cleaned_df[['left', 'top', 'width', 'height', 'text']].head())
#         print("----------------------------------------------------------------")

# except Exception as e:
#     print(f"An unexpected error occurred during processing: {e}")

# """# New Section"""

# # easyocr_to_excel_fixed.py
# import os
# from pathlib import Path
# import easyocr
# import cv2
# import pandas as pd

# # ------------- CONFIG (already set to your file) --------------
# INPUT_IMAGE = r"C:\Users\Pray\OneDrive\Desktop\Surfing.jpg"
# OUTPUT_FOLDER = r"C:\Users\Pray\OneDrive\Desktop\ocr_output"
# # ---------------------------------------------------------------

# def bbox_to_xy(bbox):
#     xs = [pt[0] for pt in bbox]
#     ys = [pt[1] for pt in bbox]
#     xmin, xmax = min(xs), max(xs)
#     ymin, ymax = min(ys), max(ys)
#     return int(round(xmin)), int(round(ymin)), int(round(xmax)), int(round(ymax))

# def annotate_and_save(img_bgr, detections, out_path):
#     img = img_bgr.copy()
#     for bbox, text, conf in detections:
#         xmin, ymin, xmax, ymax = bbox_to_xy(bbox)
#         cv2.rectangle(img, (xmin, ymin), (xmax, ymax), (0,255,0), 2)
#         label = f"{text} ({conf:.2f})"
#         (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
#         y0 = max(ymin - th - 6, 0)
#         cv2.rectangle(img, (xmin, y0), (xmin + tw + 6, y0 + th + 6), (0,255,0), -1)
#         cv2.putText(img, label, (xmin+3, y0+th+1), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
#     cv2.imwrite(str(out_path), img)

# def run_easyocr_single_image():
#     img_path = Path(INPUT_IMAGE)
#     out_dir = Path(OUTPUT_FOLDER)
#     out_dir.mkdir(parents=True, exist_ok=True)
#     annotated_dir = out_dir / 'annotated'
#     annotated_dir.mkdir(exist_ok=True)

#     # Load image
#     img_bgr = cv2.imread(str(img_path))
#     if img_bgr is None:
#         print(f"ERROR: Could not read image: {img_path}")
#         return

#     img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

#     # Run OCR (cpu)
#     reader = easyocr.Reader(['en'], gpu=False)
#     results = reader.readtext(img_rgb)

#     rows = []
#     for bbox, text, conf in results:
#         xmin, ymin, xmax, ymax = bbox_to_xy(bbox)
#         rows.append({
#             'filename': img_path.name,
#             'filepath': str(img_path),
#             'text': text,
#             'confidence': float(conf),
#             'xmin': xmin,
#             'ymin': ymin,
#             'xmax': xmax,
#             'ymax': ymax
#         })

#     # Save annotated image
#     annotated_path = annotated_dir / f"{img_path.stem}_annotated.jpg"
#     annotate_and_save(img_bgr, results, annotated_path)

#     # Save Excel file
#     df = pd.DataFrame(rows, columns=['filename','filepath','text','confidence','xmin','ymin','xmax','ymax'])
#     excel_path = out_dir / 'ocr_results.xlsx'
#     df.to_excel(str(excel_path), index=False, engine='openpyxl')

#     print(f"✔ OCR Completed")
#     print(f"✔ Excel saved to: {excel_path}")
#     print(f"✔ Annotated image saved to: {annotated_path}")

# if __name__ == "__main__":
#     run_easyocr_single_image()

# from google.colab import files
# files.download("/content/ocr_results.xlsx")
# files.download("/content/annotated.jpg")

# import easyocr
# import cv2
# import pandas as pd
# import os

# # Automatically detect uploaded file name
# image_name = list(uploaded.keys())[0]
# image_path = f"/content/{image_name}"
# output_excel = "/content/ocr_results.xlsx"
# output_annotated = "/content/annotated.jpg"

# reader = easyocr.Reader(['en'], gpu=False)

# # Load image
# img_bgr = cv2.imread(image_path)
# img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

# # OCR
# results = reader.readtext(img_rgb)

# rows = []
# for bbox, text, prob in results:
#     # bbox -> convert to xmin, ymin, xmax, ymax
#     xs = [pt[0] for pt in bbox]
#     ys = [pt[1] for pt in bbox]
#     xmin, xmax = int(min(xs)), int(max(xs))
#     ymin, ymax = int(min(ys)), int(max(ys))

#     rows.append({
#         "filename": image_name,
#         "text": text,
#         "confidence": prob,
#         "xmin": xmin,
#         "ymin": ymin,
#         "xmax": xmax,
#         "ymax": ymax
#     })

#     # draw bounding box
#     cv2.rectangle(img_bgr, (xmin, ymin), (xmax, ymax), (0,255,0), 2)
#     cv2.putText(img_bgr, text, (xmin, ymin-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)

# # Save annotated image
# cv2.imwrite(output_annotated, img_bgr)

# # Save Excel file
# df = pd.DataFrame(rows)
# df.to_excel(output_excel, index=False)

# print("✔ OCR Complete")
# print("✔ Annotated Image Saved:", output_annotated)
# print("✔ Excel Saved:", output_excel)

# !pip install easyocr opencv-python pandas openpyxl
# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# from google.colab import files
# uploaded = files.upload("Surfing.jpg")   # Upload Surfing.jpg here

# import easyocr
# import cv2
# import pandas as pd
# import os

# # Automatically detect uploaded file name
# # The 'uploaded' variable was not defined due to a previous FileExistsError.
# # Since 'Surfing.jpg' is known to exist, we can directly assign its name.
# image_name = "Visiting Card.jpg"
# image_path = f"/content/{image_name}"
# output_excel = "/content/ocr_results.xlsx"
# output_annotated = "/content/annotated.jpg"

# reader = easyocr.Reader(['en'], gpu=False)

# # Load image
# img_bgr = cv2.imread(image_path)
# img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

# # OCR
# results = reader.readtext(img_rgb)

# rows = []
# for bbox, text, prob in results:
#     # bbox -> convert to xmin, ymin, xmax, ymax
#     xs = [pt[0] for pt in bbox]
#     ys = [pt[1] for pt in bbox]
#     xmin, xmax = int(min(xs)), int(max(xs))
#     ymin, ymax = int(min(ys)), int(max(ys))

#     rows.append({
#         "filename": image_name,
#         "text": text,
#         "confidence": prob,
#         "xmin": xmin,
#         "ymin": ymin,
#         "xmax": xmax,
#         "ymax": ymax
#     })

#     # Draw bounding box
#     cv2.rectangle(img_bgr, (xmin, ymin), (xmax, ymax), (0,255,0), 2)
#     cv2.putText(img_bgr, text, (xmin, ymin-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)

# # Save annotated image
# cv2.imwrite(output_annotated, img_bgr)

# # Save Excel file
# df = pd.DataFrame(rows)
# df.to_excel(output_excel, index=False)

# print("✔ OCR Complete")
# print("✔ Annotated Image Saved:", output_annotated)
# print("✔ Excel Saved:", output_excel)

# import sys
# !pip install --upgrade easyocr

# from google.colab import files
# files.download("/content/ocr_results.xlsx")
# files.download("/content/annotated.jpg")

# # 0_install_and_setup.py  (run this cell first)
# # Installs required packages and defines helper functions.

# # --- Install packages (Colab) ---
# !pip install --quiet easyocr opencv-python-headless pandas openpyxl pdf2image

# # poppler needed by pdf2image
# !apt-get -qq install -y poppler-utils

# # --- Imports ---
# import os, io, zipfile, shutil, glob
# from pathlib import Path
# from PIL import Image
# import numpy as np
# import cv2
# import easyocr
# import pandas as pd
# from pdf2image import convert_from_path
# from google.colab import files

# # --- Configurable variables ---
# # If you want fully automated: set INPUT_PATH to a path (on Colab or Drive).
# # If INPUT_PATH is None, the script will prompt file upload (browser).
# # Examples:
# # INPUT_PATH = "/content/your_cards.zip"
# # INPUT_PATH = "/content/sample.pdf"
# # INPUT_PATH = "/content/some_folder_of_images"
# # INPUT_PATH = None  # will ask you to upload files (default)
# INPUT_PATH = None

# # Languages for EasyOCR (update as needed)
# OCR_LANGS = ['en']  # e.g. ['en','hi'] for English + Hindi

# # Use GPU? Set True if your Colab runtime has GPU
# USE_GPU = False

# # Output folder (change if desired)
# OUTPUT_DIR = Path("/content/ocr_output")
# OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# # Temp folder to extract/process images
# WORK_DIR = Path("/content/ocr_work")
# if WORK_DIR.exists():
#     shutil.rmtree(WORK_DIR)
# WORK_DIR.mkdir(parents=True, exist_ok=True)

# # Initialize easyocr reader (lazy init later)
# _reader = None
# def get_reader():
#     global _reader
#     if _reader is None:
#         print("Initializing EasyOCR reader (this may take a short while)...")
#         _reader = easyocr.Reader(OCR_LANGS, gpu=USE_GPU)
#     return _reader

# # --- Utility: save PIL image to disk with consistent format ---
# def save_pil_image(img_pil, out_path):
#     out_path = Path(out_path)
#     out_path.parent.mkdir(parents=True, exist_ok=True)
#     img_pil.save(str(out_path))
#     return str(out_path)

# # --- Extract input (upload / zip / pdf / folder) into WORK_DIR and return list of image file paths ---
# def populate_workdir(input_path=None):
#     """
#     Accepts:
#       - None -> ask user to upload files via browser (files.upload)
#       - path to zip -> extract
#       - path to pdf -> convert to images
#       - path to folder -> copy images
#       - path to single image -> copy it
#     Returns: list of absolute image paths to process
#     """
#     # allowed extensions for images
#     IMG_EXT = {'.jpg','.jpeg','.png','.bmp','.tif','.tiff','.webp'}
#     out_images = []
#     wd = WORK_DIR
#     # clear
#     if wd.exists():
#         shutil.rmtree(wd)
#     wd.mkdir(parents=True, exist_ok=True)

#     if input_path is None:
#         print("Please upload a file or multiple files in the browser upload dialog.")
#         uploaded = files.upload()
#         # uploaded is dict filename -> bytes
#         for name, data in uploaded.items():
#             local = wd / name
#             with open(local, "wb") as f:
#                 f.write(data)
#             print("Uploaded:", name)
#             # handle based on extension below
#             ext = Path(name).suffix.lower()
#             if ext == '.zip':
#                 _extract_zip(local, wd)
#             elif ext == '.pdf':
#                 _pdf_to_images(local, wd)
#             elif ext in IMG_EXT:
#                 out_images.append(str(local))
#             else:
#                 print("Skipped uploaded file (unsupported ext):", name)
#         # after possibly extracting zip/pdf, collect images
#     else:
#         ip = Path(input_path)
#         if not ip.exists():
#             raise FileNotFoundError(f"Input path not found: {input_path}")
#         if ip.suffix.lower() == '.zip':
#             _extract_zip(ip, wd)
#         elif ip.suffix.lower() == '.pdf':
#             _pdf_to_images(ip, wd)
#         elif ip.is_file() and ip.suffix.lower() in IMG_EXT:
#             # single image
#             dst = wd / ip.name
#             shutil.copy(str(ip), str(dst))
#         elif ip.is_dir():
#             # copy images from folder
#             for p in ip.rglob("*"):
#                 if p.suffix.lower() in IMG_EXT:
#                     dst = wd / p.name
#                     shutil.copy(str(p), str(dst))
#         else:
#             raise ValueError("Unsupported input type: " + str(ip))

#     # gather images inside wd
#     for p in sorted(wd.rglob("*")):
#         if p.suffix.lower() in IMG_EXT:
#             out_images.append(str(p))
#     if not out_images:
#         print("Warning: no image files found to process.")
#     return out_images

# def _extract_zip(zip_path, dest_dir):
#     print("Extracting zip:", zip_path)
#     with zipfile.ZipFile(zip_path, 'r') as z:
#         z.extractall(dest_dir)
#     return

# def _pdf_to_images(pdf_path, dest_dir, dpi=200):
#     print("Converting PDF to images:", pdf_path)
#     pages = convert_from_path(str(pdf_path), dpi=dpi)
#     for i, page in enumerate(pages):
#         fname = dest_dir / f"{Path(pdf_path).stem}_page_{i+1}.jpg"
#         save_pil_image(page, fname)
#     return

# # --- OCR & annotate an image (returns list of detections) ---
# def ocr_and_annotate(image_path, out_annotated_dir):
#     """
#     image_path: path to image
#     out_annotated_dir: directory to save annotated image
#     returns: list of dicts with keys: filename,text,confidence,xmin,ymin,xmax,ymax
#     """
#     reader = get_reader()
#     img_bgr = cv2.imread(str(image_path))
#     if img_bgr is None:
#         print("Failed to read:", image_path)
#         return []
#     img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
#     # EasyOCR returns list of (bbox, text, prob)
#     try:
#         results = reader.readtext(img_rgb)
#     except Exception as e:
#         print("OCR failed on", image_path, ":", e)
#         results = []

#     rows = []
#     # draw on a copy
#     out_img = img_rgb.copy()
#     for bbox, text, conf in results:
#         # bbox is list of 4 points [[x1,y1],[x2,y2],[x3,y3],[x4,y4]]
#         xs = [int(round(p[0])) for p in bbox]
#         ys = [int(round(p[1])) for p in bbox]
#         xmin, xmax = min(xs), max(xs)
#         ymin, ymax = min(ys), max(ys)
#         rows.append({
#             "filename": Path(image_path).name,
#             "filepath": str(image_path),
#             "text": text,
#             "confidence": float(conf),
#             "xmin": int(xmin),
#             "ymin": int(ymin),
#             "xmax": int(xmax),
#             "ymax": int(ymax),
#         })
#         # draw rectangle and text
#         cv2.rectangle(out_img, (xmin, ymin), (xmax, ymax), (0,255,0), 2)
#         # prepare label
#         label = f"{text} ({conf:.2f})"
#         # place label
#         tsize = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)[0]
#         tx = xmin
#         ty = max(0, ymin - 8)
#         cv2.rectangle(out_img, (tx, ty - tsize[1] - 4), (tx + tsize[0] + 4, ty + 4), (0,255,0), -1)
#         cv2.putText(out_img, label, (tx+2, ty), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)

#     # save annotated image
#     out_annotated_dir = Path(out_annotated_dir)
#     out_annotated_dir.mkdir(parents=True, exist_ok=True)
#     annotated_path = out_annotated_dir / f"{Path(image_path).stem}_annotated{Path(image_path).suffix}"
#     # convert rgb -> bgr for saving
#     cv2.imwrite(str(annotated_path), cv2.cvtColor(out_img, cv2.COLOR_RGB2BGR))

#     return rows, str(annotated_path)

# # 1_run_pipeline.py  (run this cell after the previous one)
# # It will automatically ask for upload if INPUT_PATH is None,
# # otherwise it will use INPUT_PATH. Change INPUT_PATH and re-run if you want different input.

# # --- Populate workdir and get image paths ---
# image_paths = populate_workdir(INPUT_PATH)
# print("Found images to process:", len(image_paths))
# if len(image_paths) == 0:
#     print("No images found. If you uploaded a zip, ensure it contains image files.")
# else:
#     # prepare output folders
#     annotated_folder = OUTPUT_DIR / "annotated"
#     annotated_folder.mkdir(parents=True, exist_ok=True)
#     all_rows = []

#     # process each image
#     for img_p in image_paths:
#         print("Processing:", img_p)
#         rows, annotated_path = ocr_and_annotate(img_p, annotated_folder)
#         print("  detections:", len(rows), "-> annotated saved:", annotated_path)
#         all_rows.extend(rows)

#     # save results to CSV and Excel
#     df = pd.DataFrame(all_rows, columns=['filename','filepath','text','confidence','xmin','ymin','xmax','ymax'])
#     csv_path = OUTPUT_DIR / "ocr_results.csv"
#     excel_path = OUTPUT_DIR / "ocr_results.xlsx"
#     df.to_csv(csv_path, index=False, encoding='utf-8')
#     df.to_excel(excel_path, index=False, engine='openpyxl')
#     print("✔ Saved CSV:", csv_path)
#     print("✔ Saved Excel:", excel_path)

#     # zip annotated images and results for download convenience
#     zip_out = "/content/ocr_output_bundle.zip"
#     with zipfile.ZipFile(zip_out, 'w') as zf:
#         # write excel and csv
#         zf.write(str(csv_path), arcname="ocr_results.csv")
#         zf.write(str(excel_path), arcname="ocr_results.xlsx")
#         # write annotated images
#         for p in sorted(annotated_folder.rglob("*")):
#             zf.write(str(p), arcname=os.path.join("annotated", p.name))
#     print("✔ Created bundle:", zip_out)

#     # provide download links (Colab)
#     from google.colab import files as gfiles
#     print("You can download these files:")
#     display_paths = [str(excel_path), str(csv_path), zip_out]
#     for p in display_paths:
#         print("-", p)
#     # Optionally start downloads automatically:
#     # for p in display_paths:
#     #     gfiles.download(p)

# ==== IMPORTS & GLOBALS (FIX MISSING STUFF) ====
import os
import zipfile
from pathlib import Path

import pandas as pd

try:
    from google.colab import files as gfiles
except ImportError:
    gfiles = None  # if not in Colab

# Set these as you like
# If INPUT_PATH is None -> it will ask you to upload in Colab
INPUT_PATH = None              # e.g. "/content/my_images.zip" or None
WORKDIR = Path("/content/workdir")
OUTPUT_DIR = Path("/content/ocr_output")
WORKDIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ==== HELPER: populate_workdir (RECTIFIES undefined function) ====
def populate_workdir(input_path=None):
    """
    Returns a list of image paths.
    - If input_path is None: asks user to upload (Colab).
    - If input_path is a zip: extracts into WORKDIR and returns images.
    - If input_path is a folder: returns all images inside.
    - If input_path is a single image: returns list with that image.
    """

    exts = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}

    # 1) If no path given, ask user to upload (Colab)
    if input_path is None:
        if gfiles is None:
            print("No INPUT_PATH and not in Colab. Please set INPUT_PATH to a file/folder.")
            return []
        print("No INPUT_PATH set. Please upload a zip or image file...")
        uploaded = gfiles.upload()
        if not uploaded:
            return []
        fname = list(uploaded.keys())[0]
        input_path = str(Path.cwd() / fname)

    input_path = Path(input_path)

    # 2) If path is a zip file
    if input_path.is_file() and input_path.suffix.lower() == ".zip":
        print(f"Detected zip file: {input_path}")
        with zipfile.ZipFile(str(input_path), 'r') as zf:
            zf.extractall(str(WORKDIR))
        # collect images
        image_paths = [
            p for p in WORKDIR.rglob("*")
            if p.suffix.lower() in exts
        ]
        return sorted(image_paths)

    # 3) If path is a folder -> collect images inside
    if input_path.is_dir():
        image_paths = [
            p for p in input_path.rglob("*")
            if p.suffix.lower() in exts
        ]
        return sorted(image_paths)

    # 4) If path is a single image
    if input_path.is_file() and input_path.suffix.lower() in exts:
        return [input_path]

    print("No valid images found for:", input_path)
    return []


# ==== PLACEHOLDER OCR FUNCTION (RECTIFY undefined ocr_and_annotate) ====
# !!! REPLACE THIS WITH YOUR REAL OCR FUNCTION !!!
def ocr_and_annotate(img_path, annotated_folder):
    """
    Dummy implementation.
    Expected to return:
      rows: list of [filename, filepath, text, confidence, xmin, ymin, xmax, ymax]
      annotated_path: Path to annotated image
    Replace this body with your existing OCR code that you already have working.
    """
    # Example dummy output; replace with real OCR
    filename = img_path.name
    text = "dummy text from OCR"
    confidence = 0.99
    xmin, ymin, xmax, ymax = 0, 0, 100, 50

    # "annotated" image path (here we just reuse original)
    annotated_path = annotated_folder / filename
    annotated_path.write_bytes(img_path.read_bytes())  # copy image

    rows = [[filename, str(img_path), text, confidence, xmin, ymin, xmax, ymax]]
    return rows, annotated_path


# ==== ORIGINAL PIPELINE CODE (NOW WORKING) ====
# It will automatically ask for upload if INPUT_PATH is None,
# otherwise it will use INPUT_PATH. Change INPUT_PATH and re-run if you want different input.

image_paths = populate_workdir(INPUT_PATH)
print("Found images to process:", len(image_paths))

if len(image_paths) == 0:
    print("No images found. If you uploaded a zip, ensure it contains image files.")
else:
    # prepare output folders
    annotated_folder = OUTPUT_DIR / "annotated"
    annotated_folder.mkdir(parents=True, exist_ok=True)
    all_rows = []

    # process each image
    for img_p in image_paths:
        print("Processing:", img_p)
        rows, annotated_path = ocr_and_annotate(img_p, annotated_folder)
        print("  detections:", len(rows), "-> annotated saved:", annotated_path)
        all_rows.extend(rows)

    # save results to CSV and Excel
    df = pd.DataFrame(
        all_rows,
        columns=[
            'filename','filepath','text','confidence',
            'xmin','ymin','xmax','ymax'
        ]
    )

    csv_path = OUTPUT_DIR / "ocr_results.csv"
    excel_path = OUTPUT_DIR / "ocr_results.xlsx"

    df.to_csv(csv_path, index=False, encoding='utf-8')
    df.to_excel(excel_path, index=False, engine='openpyxl')
    print("✔ Saved CSV:", csv_path)
    print("✔ Saved Excel:", excel_path)

    # zip annotated images and results for download convenience
    zip_out = "/content/ocr_output_bundle.zip"
    with zipfile.ZipFile(zip_out, 'w') as zf:
        # write excel and csv
        zf.write(str(csv_path), arcname="ocr_results.csv")
        zf.write(str(excel_path), arcname="ocr_results.xlsx")
        # write annotated images
        for p in sorted(annotated_folder.rglob("*")):
            zf.write(str(p), arcname=os.path.join("annotated", p.name))
    print("✔ Created bundle:", zip_out)

    # provide download links (Colab)
    if gfiles is not None:
        print("You can download these files:")
        display_paths = [str(excel_path), str(csv_path), zip_out]
        for p in display_paths:
            print("-", p)
        # To auto-download uncomment:
        # for p in display_paths:
        #     gfiles.download(p)
    else:
        print("Not running in Colab, so automatic download links are skipped.")

# 2_download_outputs.py  (run to download results)
from google.colab import files
files.download("/content/ocr_output/ocr_results.xlsx")
files.download("/content/ocr_output/ocr_results.csv")
files.download("/content/ocr_output_bundle.zip")